---
- name: Initializing of swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

- name: Availability of directory
  local_action:
    module: file
    path: ./tokens
    state: directory
    mode: '0777'

- name: Save token manager
  local_action:
    module: copy
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"
    mode: '0644'
  delegate_to: localhost

- name: Save token worker
  local_action:
    module: copy
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"
    mode: '0644'
