---
- name: "[{{ name }}] Secret configuration"
  block:
   - name: "[{{ name }}] Secret creation"
     include: "secret-create.yml"
  tags: "{{ name }}"
  rescue:
   - name: "[{{ name }}] Service delete"
     community.docker.docker_swarm_service:
      name: "{{ name }}"
      state: absent

   - name: "[{{ name }}] Secret creation"
     include: "secret-create.yml"
